import { THEME_NAMES, type ThemeName, type ThemeTokens } from './colors';

const BASE_STRUCTURE: Pick<ThemeTokens, '--sf-radius-sm' | '--sf-radius-full' | '--sf-font-mono'> = {
  '--sf-radius-sm': '4px',
  '--sf-radius-full': '9999px',
  '--sf-font-mono': "'Geist Mono', ui-monospace, monospace",
};

export const THEME_DEFINITIONS: Record<ThemeName, ThemeTokens> = {
  dark: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#09090b',
    '--sf-bg-surface': '#18181b',
    '--sf-bg-elevated': '#27272a',
    '--sf-bg-overlay': '#3f3f46',
    '--sf-text': '#fafafa',
    '--sf-text-secondary': '#a1a1aa',
    '--sf-text-muted': '#71717a',
    '--sf-text-disabled': '#52525b',
    '--sf-border': '#27272a',
    '--sf-border-strong': '#3f3f46',
    '--sf-accent': '#3b82f6',
    '--sf-accent-hover': '#2563eb',
    '--sf-destructive': '#ef4444',
    '--sf-success': '#22c55e',
    '--sf-warning': '#eab308',
    '--sf-radius-md': '6px',
    '--sf-radius-lg': '8px',
    '--sf-radius-xl': '12px',
    '--sf-border-width': '1px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '150ms',
  },
  light: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#fafafa',
    '--sf-bg-surface': '#ffffff',
    '--sf-bg-elevated': '#f4f4f5',
    '--sf-bg-overlay': '#e4e4e7',
    '--sf-text': '#18181b',
    '--sf-text-secondary': '#52525b',
    '--sf-text-muted': '#a1a1aa',
    '--sf-text-disabled': '#d4d4d8',
    '--sf-border': '#e4e4e7',
    '--sf-border-strong': '#a1a1aa',
    '--sf-accent': '#2563eb',
    '--sf-accent-hover': '#1d4ed8',
    '--sf-destructive': '#dc2626',
    '--sf-success': '#16a34a',
    '--sf-warning': '#ca8a04',
    '--sf-radius-md': '6px',
    '--sf-radius-lg': '8px',
    '--sf-radius-xl': '12px',
    '--sf-border-width': '1px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '150ms',
  },
  ember: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#1a0f05',
    '--sf-bg-surface': '#2a1a0a',
    '--sf-bg-elevated': '#3d2814',
    '--sf-bg-overlay': '#4d3520',
    '--sf-text': '#fef3c7',
    '--sf-text-secondary': '#d4a574',
    '--sf-text-muted': '#9a7a52',
    '--sf-text-disabled': '#6b5030',
    '--sf-border': '#3d2814',
    '--sf-border-strong': '#5c3d1e',
    '--sf-accent': '#f59e0b',
    '--sf-accent-hover': '#d97706',
    '--sf-destructive': '#ef4444',
    '--sf-success': '#22c55e',
    '--sf-warning': '#fbbf24',
    '--sf-radius-md': '8px',
    '--sf-radius-lg': '10px',
    '--sf-radius-xl': '14px',
    '--sf-border-width': '1px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '200ms',
  },
  rust: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#1c1917',
    '--sf-bg-surface': '#292524',
    '--sf-bg-elevated': '#44403c',
    '--sf-bg-overlay': '#57534e',
    '--sf-text': '#fafaf9',
    '--sf-text-secondary': '#a8a29e',
    '--sf-text-muted': '#78716c',
    '--sf-text-disabled': '#57534e',
    '--sf-border': '#44403c',
    '--sf-border-strong': '#57534e',
    '--sf-accent': '#ea580c',
    '--sf-accent-hover': '#c2410c',
    '--sf-destructive': '#dc2626',
    '--sf-success': '#16a34a',
    '--sf-warning': '#ca8a04',
    '--sf-radius-md': '4px',
    '--sf-radius-lg': '6px',
    '--sf-radius-xl': '8px',
    '--sf-border-width': '2px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '100ms',
  },
  ice: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#0f172a',
    '--sf-bg-surface': '#1e293b',
    '--sf-bg-elevated': '#334155',
    '--sf-bg-overlay': '#475569',
    '--sf-text': '#f1f5f9',
    '--sf-text-secondary': '#94a3b8',
    '--sf-text-muted': '#64748b',
    '--sf-text-disabled': '#475569',
    '--sf-border': '#334155',
    '--sf-border-strong': '#475569',
    '--sf-accent': '#22d3ee',
    '--sf-accent-hover': '#06b6d4',
    '--sf-destructive': '#fb7185',
    '--sf-success': '#34d399',
    '--sf-warning': '#fbbf24',
    '--sf-radius-md': '2px',
    '--sf-radius-lg': '4px',
    '--sf-radius-xl': '6px',
    '--sf-border-width': '1px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '120ms',
  },
  leaf: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#0a1a0f',
    '--sf-bg-surface': '#132a1a',
    '--sf-bg-elevated': '#1e3d24',
    '--sf-bg-overlay': '#2d5438',
    '--sf-text': '#ecfdf5',
    '--sf-text-secondary': '#6ee7a0',
    '--sf-text-muted': '#4aba6e',
    '--sf-text-disabled': '#2d7a42',
    '--sf-border': '#1e3d24',
    '--sf-border-strong': '#2d5438',
    '--sf-accent': '#10b981',
    '--sf-accent-hover': '#059669',
    '--sf-destructive': '#ef4444',
    '--sf-success': '#22c55e',
    '--sf-warning': '#eab308',
    '--sf-radius-md': '10px',
    '--sf-radius-lg': '12px',
    '--sf-radius-xl': '16px',
    '--sf-border-width': '1px',
    '--sf-font-ui': "'Geist Sans', system-ui, sans-serif",
    '--sf-transition': '180ms',
  },
  mech: {
    ...BASE_STRUCTURE,
    '--sf-bg-app': '#0c0c0e',
    '--sf-bg-surface': '#141418',
    '--sf-bg-elevated': '#1e1e24',
    '--sf-bg-overlay': '#28283a',
    '--sf-text': '#e0e0e8',
    '--sf-text-secondary': '#8888a0',
    '--sf-text-muted': '#606078',
    '--sf-text-disabled': '#404058',
    '--sf-border': '#1e1e30',
    '--sf-border-strong': '#2e2e48',
    '--sf-accent': '#00ff88',
    '--sf-accent-hover': '#00cc6a',
    '--sf-destructive': '#ff3366',
    '--sf-success': '#00cc66',
    '--sf-warning': '#ffaa00',
    '--sf-radius-md': '1px',
    '--sf-radius-lg': '2px',
    '--sf-radius-xl': '4px',
    '--sf-border-width': '2px',
    '--sf-font-ui': "'Geist Mono', ui-monospace, monospace",
    '--sf-transition': '80ms',
  },
};

/** Generate CSS custom properties block for a theme */
export function generateThemeCSS(theme: ThemeName): string {
  const tokens = THEME_DEFINITIONS[theme];
  return Object.entries(tokens)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n');
}

/** Generate all theme CSS blocks */
export function generateAllThemeCSS(): string {
  return THEME_NAMES.map(
    (name) => `:root[data-sf-theme="${name}"] {\n${generateThemeCSS(name)}\n}`
  ).join('\n\n');
}
