"""Regenerate the OG guard from exact bundled cmap coverage; use --check for local freshness."""
from pathlib import Path
import hashlib
import sys
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parents[1]
assets = root / 'src/assets/fonts'
files = ['NotoSans-Regular.ttf', 'NotoSans-Bold.ttf', 'SpawnForgeArabic-Regular.ttf', 'NotoSansCJKjp-Regular.otf']
points = {9, 10, 13}  # Satori handles these layout controls without font glyphs.
hashes = {}
for name in files:
    path = assets / name
    hashes[name] = hashlib.sha256(path.read_bytes()).hexdigest()
    with TTFont(path) as font:
        points.update(font.getBestCmap().keys())
ranges = []
for point in sorted(points):
    if ranges and point == ranges[-1][1] + 1:
        ranges[-1][1] = point
    else:
        ranges.append([point, point])
lines = ['// Generated by web/scripts/generate-og-font-coverage.py; do not edit.',
         '// Exact Unicode cmap union of the bundled OG fonts, plus layout whitespace.',
         'export const PLAY_CARD_FONT_SHA256 = {']
lines += ["  '" + name + "': '" + digest + "'," for name, digest in hashes.items()]
lines += ['} as const;', '', 'export const PLAY_CARD_GLYPH_RANGES: ReadonlyArray<readonly [number, number]> = [']
lines += ['  [0x%X, 0x%X],' % tuple(span) for span in ranges]
lines += ['];', '']
source = '\n'.join(lines)
output = root / 'src/lib/og/play-card-glyphs.ts'
if '--check' in sys.argv:
    if not output.exists() or output.read_text(encoding='utf8') != source:
        raise SystemExit('OG glyph coverage is stale; regenerate from the checked-in fonts')
else:
    output.write_text(source, encoding='utf8', newline='\n')
print('Verified %d code points in %d ranges' % (len(points), len(ranges)))
