-- Migration: YYYY-MM-DD_description_of_change
-- Generated by: npm run db:generate (Drizzle Kit)
-- Applied by:   npm run db:migrate (production) | npm run db:push (dev only)
--
-- Instructions:
--   1. Replace the description in the filename and comment above.
--   2. Never edit a migration that has already been applied to production.
--   3. Always wrap destructive changes (DROP COLUMN, DROP TABLE) in a transaction.
--   4. Add new columns as NULLABLE first, then backfill, then add NOT NULL constraint.
--   5. Use IF NOT EXISTS / IF EXISTS guards for safety.

BEGIN;

-- ============================================================
-- Example: Add a new column to an existing table
-- ============================================================
-- ALTER TABLE "public"."projects"
--   ADD COLUMN IF NOT EXISTS "published_at" timestamp;

-- ============================================================
-- Example: Create a new table
-- ============================================================
-- CREATE TABLE IF NOT EXISTS "public"."example_table" (
--   "id"         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   "user_id"    uuid NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,
--   "name"       text NOT NULL,
--   "metadata"   jsonb NOT NULL DEFAULT '{}',
--   "created_at" timestamp NOT NULL DEFAULT NOW(),
--   "updated_at" timestamp NOT NULL DEFAULT NOW()
-- );

-- ============================================================
-- Example: Create an index
-- ============================================================
-- CREATE INDEX IF NOT EXISTS "idx_example_table_user_id"
--   ON "public"."example_table" ("user_id");

-- ============================================================
-- Example: Data migration — backfill a new column
-- (Run BEFORE adding NOT NULL constraint)
-- ============================================================
-- UPDATE "public"."projects"
--   SET "published_at" = "created_at"
--   WHERE "published_at" IS NULL AND "is_published" = true;

-- ============================================================
-- Example: Add NOT NULL after backfill
-- ============================================================
-- ALTER TABLE "public"."projects"
--   ALTER COLUMN "published_at" SET NOT NULL;

-- ============================================================
-- Example: Rename a column (safe — no data loss)
-- ============================================================
-- ALTER TABLE "public"."projects"
--   RENAME COLUMN "old_name" TO "new_name";

-- ============================================================
-- Example: Drop a column (DESTRUCTIVE — verify backups)
-- ============================================================
-- ALTER TABLE "public"."projects"
--   DROP COLUMN IF EXISTS "deprecated_field";

COMMIT;
