import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, lazy } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { NextIntlClientProvider } from "next-intl";
import { defaultLocale } from "@/i18n/config";
import messages from "@/i18n/messages/en.json";
import { Toaster } from "sonner";
import { ServiceWorkerRegistration } from "@/components/ServiceWorkerRegistration";
import "./globals.css";

// Lazy-load analytics and consent providers — they rely on browser APIs
// (localStorage, window) and are not needed for the initial HTML render.
// Deferring them reduces the client JS parsed on the critical path.
const AnalyticsProvider = lazy(() => import("@/components/AnalyticsProvider").then((m) => ({ default: m.AnalyticsProvider })));
const PostHogProvider = lazy(() => import("@/components/providers/PostHogProvider").then((m) => ({ default: m.PostHogProvider })));
const CookieConsent = lazy(() => import("@/components/CookieConsent").then((m) => ({ default: m.CookieConsent })));

// Root layout was previously force-dynamic because getMessages() reads request context.
// Replaced with static import of en.json (single locale) to allow static rendering
// of marketing pages — improves LCP by ~1s on cold loads.

// Clerk validates key format at runtime — skip wrapping when key is missing/invalid (CI E2E tests)
const clerkKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ?? "";
const hasValidClerkKey = clerkKey.startsWith("pk_test_") || clerkKey.startsWith("pk_live_");

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://spawnforge.ai";

export const metadata: Metadata = {
  title: "SpawnForge",
  description: "AI-Powered Game Creation Platform — build 2D and 3D games in your browser with natural language and a visual editor.",
  manifest: "/manifest.json",
  openGraph: {
    title: "SpawnForge",
    description: "AI-Powered Game Creation Platform — build 2D and 3D games in your browser with natural language and a visual editor.",
    url: SITE_URL,
    siteName: "SpawnForge",
    type: "website",
    // OG image auto-generated by app/opengraph-image.tsx (file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: "SpawnForge",
    description: "AI-Powered Game Creation Platform — build 2D and 3D games in your browser.",
    // Twitter falls back to OG image from app/opengraph-image.tsx
  },
};

// Static JSON-LD Organization schema (safe constant — no user input)
const jsonLdString = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "SpawnForge",
  url: SITE_URL,
  logo: `${SITE_URL}/favicon.ico`,
  description: "AI-Powered Game Creation Platform — build 2D and 3D games in your browser with natural language and a visual editor.",
  sameAs: [],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // messages imported statically from en.json (single locale — no getMessages() needed)

  // Clerk v7 requires ClerkProvider to be inside <body>, not wrapping <html>.
  const bodyContent = (
    <>
      {/* JSON-LD structured data injected here; search engines read it from
          body per Schema.org and Google guidelines. Manual <head> tags are
          not permitted in Next.js App Router layouts (metadata export manages
          all head injection). jsonLdString is JSON.stringify of a static
          constant — no user input, no XSS risk. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdString }}
      />
      <NextIntlClientProvider locale={defaultLocale} messages={messages}>
        <Suspense>{children}</Suspense>
      </NextIntlClientProvider>
      <Suspense fallback={null}>
        <AnalyticsProvider />
        <PostHogProvider />
        <CookieConsent />
      </Suspense>
      <SpeedInsights />
      <Toaster theme="dark" position="bottom-right" richColors />
      <ServiceWorkerRegistration />
    </>
  );

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {hasValidClerkKey ? (
          <ClerkProvider appearance={{ baseTheme: dark }} afterSignOutUrl="/sign-in">
            {bodyContent}
          </ClerkProvider>
        ) : (
          bodyContent
        )}
      </body>
    </html>
  );
}
