#!/usr/bin/env bash
# Codex CLI surface drift gate — fail a PR when the generated Codex surface
# (.agents/skills/<project skills>, .codex/agents/*.toml, .codex/hooks.json) no
# longer matches its source under .claude/, when any `.codex/` file names a
# path under .claude/, .codex/, .agents/ or .github/ that does not exist (those
# four roots only — a reference to docs/ or scripts/ is NOT resolved), or when
# `.codex/config.toml` and `.mcp.json` declare different MCP servers.
#
# WHY IT EXISTS
# The first port of .claude/ to Codex was made by hand and rotted inside a week:
# 143 references to `.Codex/rules`, `.Codex/tools` and `.Codex/skills`
# (directories that do not exist), 26 of 39 hooks wired, skills already drifted
# from their originals. It was quarantined in .gitignore under #9745. The port
# is now GENERATED by tools/agentic-sync/port.mjs; this gate runs that generator
# in --check mode so the mirror cannot drift again without a red PR. It is the
# #9745 acceptance scenario made permanent: "a reference names nonexistent
# .Codex/rules → validation fails with the exact unresolved path".
#
# All decision logic lives in the generator, where the hermetic suite can reach
# it through one seam. This wrapper only locates node and the generator, and
# turns "could not run" into a failure rather than a pass.
#
# Mirrors scripts/check-agentic-sync.sh: self-contained, seconds long, gated on
# the ci-gate `needs-agentic` output, a CHECK and never a fix (--check does not
# write). Unit-tested by scripts/__tests__/check-codex-port.test.sh.
#
# Exit 0 = in sync. Exit 1 = drift, an unresolved reference, or MCP servers out
# of parity. Exit 2 = the gate could not run (no node, missing generator,
# malformed manifest, an unclassified hook) — fail-closed.
#
# $CODEX_PORT_NODE is a TEST-ONLY override of the node binary, honoured only
# OUTSIDE CI, so an injected env var can never redirect the invocation there.
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT" || { echo "::error::could not cd to repo root" >&2; exit 2; }

GEN="tools/agentic-sync/port.mjs"
if [ "${CI:-}" = "true" ]; then
  NODE_BIN="node"
else
  NODE_BIN="${CODEX_PORT_NODE:-node}"
fi

if ! command -v "$NODE_BIN" >/dev/null 2>&1; then
  echo "::error::'$NODE_BIN' not found — cannot run the Codex port drift check" >&2
  exit 2
fi
if [ ! -f "$GEN" ]; then
  echo "::error::$GEN not found at repo root ($ROOT)" >&2
  exit 2
fi

"$NODE_BIN" "$GEN" --check
rc=$?
if [ "$rc" -eq 0 ]; then
  echo "✓ Codex CLI surface is in sync with .claude/."
  exit 0
fi
if [ "$rc" -eq 1 ]; then
  # Nothing is added here. The generator has already printed a recipe for each
  # KIND of problem it listed, and they differ: drift is fixed by regenerating,
  # while `mcp:` and `ref:` are fixed by editing a hand-written .codex/ file. A
  # blanket "never hand-edit it" as the last line of the log contradicted those.
  exit 1
fi
echo "::error::the Codex port generator could not run (exit $rc) — treating as a failure, not a pass" >&2
exit 2
