import { describe, it, expect } from 'vitest';
import { compileGraph } from './graphCompiler';
import type { VisualScriptGraph } from './visualScriptTypes';

describe('graphCompiler', () => {
  it('compiles empty graph with warning', () => {
    const graph: VisualScriptGraph = { nodes: [], edges: [] };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('Generated by Visual Script Compiler');
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings[0].message).toContain('No event nodes found');
  });

  it('compiles OnStart + SetPosition', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'SetPosition', position: { x: 200, y: 0 }, data: { entity: 'entityId', position: '[0, 5, 0]' } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('function onStart()');
    expect(result.code).toContain('forge.setPosition');
    expect(result.code).toContain('entityId');
    expect(result.errors.length).toBe(0);
  });

  it('compiles OnUpdate + Translate (basic movement)', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnUpdate', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'Translate', position: { x: 200, y: 0 }, data: { entity: 'entityId', dx: 0, dy: 0, dz: 1 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('function onUpdate(dt: number)');
    expect(result.code).toContain('forge.translate');
    expect(result.code).toContain('entityId');
    expect(result.code).toContain('0, 0, 1');
    expect(result.errors.length).toBe(0);
  });

  it('compiles Branch node with condition', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnUpdate', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'IsPressed', position: { x: 100, y: 100 }, data: { action: 'jump' } },
        { id: '3', type: 'Branch', position: { x: 200, y: 0 }, data: {} },
        { id: '4', type: 'ApplyImpulse', position: { x: 400, y: 0 }, data: { entity: 'entityId', fx: 0, fy: 10, fz: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '3', targetHandle: 'exec_in' },
        { id: 'e2', source: '2', sourceHandle: 'pressed', target: '3', targetHandle: 'condition' },
        { id: 'e3', source: '3', sourceHandle: 'exec_true', target: '4', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('if (forge.input.isPressed("jump"))');
    expect(result.code).toContain('forge.physics.applyImpulse');
    expect(result.code).toContain('0, 10, 0');
    expect(result.errors.length).toBe(0);
  });

  it('compiles SetVariable + GetVariable', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'SetVariable', position: { x: 200, y: 0 }, data: { key: 'score', value: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.state.set');
    expect(result.code).toContain('"score"');
    expect(result.code).toContain('0');
    expect(result.errors.length).toBe(0);
  });

  it('compiles math data chain (GetAxis + Multiply + Translate)', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnUpdate', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'GetAxis', position: { x: 100, y: 50 }, data: { action: 'move_right' } },
        { id: '3', type: 'Multiply', position: { x: 250, y: 50 }, data: { b: 5 } },
        { id: '4', type: 'Translate', position: { x: 400, y: 0 }, data: { entity: 'entityId', dy: 0, dz: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '4', targetHandle: 'exec_in' },
        { id: 'e2', source: '2', sourceHandle: 'value', target: '3', targetHandle: 'a' },
        { id: 'e3', source: '3', sourceHandle: 'result', target: '4', targetHandle: 'dx' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.input.getAxis("move_right")');
    expect(result.code).toContain('* 5');
    expect(result.code).toContain('forge.translate');
    expect(result.errors.length).toBe(0);
  });

  it('warns on disconnected nodes', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'Translate', position: { x: 200, y: 200 }, data: {} },
      ],
      edges: [],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings.some(w => w.message.includes('disconnected'))).toBe(true);
  });

  it('compiles SpawnEntity node', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'SpawnEntity', position: { x: 200, y: 0 }, data: { type: 'sphere', name: 'ball', x: 0, y: 5, z: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.spawn');
    expect(result.code).toContain('"sphere"');
    expect(result.code).toContain('"ball"');
    expect(result.code).toContain('position: [0, 5, 0]');
    expect(result.errors.length).toBe(0);
  });

  it('compiles ForLoop with body', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'ForLoop', position: { x: 200, y: 0 }, data: { start: 0, end: 5 } },
        { id: '3', type: 'SpawnEntity', position: { x: 400, y: 0 }, data: { type: 'cube', name: 'box', x: 0, y: 0, z: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
        { id: 'e2', source: '2', sourceHandle: 'exec_body', target: '3', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('for (let i = 0; i < 5; i++)');
    expect(result.code).toContain('forge.spawn');
    expect(result.code).toContain('"cube"');
    expect(result.errors.length).toBe(0);
  });

  it('compiles complex data flow (Add + MakeVec3 + SetPosition)', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnUpdate', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'Add', position: { x: 100, y: 50 }, data: { a: 1, b: 2 } },
        { id: '3', type: 'MakeVec3', position: { x: 250, y: 50 }, data: { x: 0, z: 0 } },
        { id: '4', type: 'SetPosition', position: { x: 400, y: 0 }, data: { entity: 'entityId' } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '4', targetHandle: 'exec_in' },
        { id: 'e2', source: '2', sourceHandle: 'result', target: '3', targetHandle: 'y' },
        { id: 'e3', source: '3', sourceHandle: 'vec3', target: '4', targetHandle: 'position' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('(1 + 2)');
    expect(result.code).toContain('[0, (1 + 2), 0]');
    expect(result.code).toContain('forge.setPosition');
    expect(result.errors.length).toBe(0);
  });

  it('compiles collision event handler', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnCollisionEnter', position: { x: 0, y: 0 }, data: { entity: 'entityId' } },
        { id: '2', type: 'PlaySound', position: { x: 200, y: 0 }, data: { entity: 'soundEntityId' } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.physics.onCollisionEnter');
    expect(result.code).toContain('otherEntityId');
    expect(result.code).toContain('forge.audio.play');
    expect(result.errors.length).toBe(0);
  });

  it('compiles UI ShowText node', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'ShowText', position: { x: 200, y: 0 }, data: { id: 'score_label', text: 'Score: 0', x: 10, y: 10 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.ui.showText');
    expect(result.code).toContain('"score_label"');
    expect(result.code).toContain('"Score: 0"');
    expect(result.code).toContain('10, 10');
    expect(result.errors.length).toBe(0);
  });

  it('compiles timer event with state tracking', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnTimer', position: { x: 0, y: 0 }, data: { interval: 2 } },
        { id: '2', type: 'SpawnEntity', position: { x: 200, y: 0 }, data: { type: 'sphere', name: 'enemy', x: 0, y: 5, z: 0 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('let _timer_1_elapsed = 0');
    expect(result.code).toContain('_timer_1_elapsed += dt');
    expect(result.code).toContain('if (_timer_1_elapsed >= 2)');
    expect(result.code).toContain('_timer_1_elapsed = 0');
    expect(result.errors.length).toBe(0);
  });

  it('compiles Distance and GetPosition data nodes', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnUpdate', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'GetPosition', position: { x: 100, y: 50 }, data: { entity: 'player' } },
        { id: '3', type: 'GetPosition', position: { x: 100, y: 150 }, data: { entity: 'enemy' } },
        { id: '4', type: 'Distance', position: { x: 250, y: 100 }, data: {} },
        { id: '5', type: 'Branch', position: { x: 400, y: 0 }, data: {} },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '5', targetHandle: 'exec_in' },
        { id: 'e2', source: '2', sourceHandle: 'position', target: '4', targetHandle: 'a' },
        { id: 'e3', source: '3', sourceHandle: 'position', target: '4', targetHandle: 'b' },
        { id: 'e4', source: '4', sourceHandle: 'distance', target: '5', targetHandle: 'condition' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('forge.getTransform("player")');
    expect(result.code).toContain('forge.getTransform("enemy")');
    expect(result.code).toContain('Math.sqrt');
    expect(result.errors.length).toBe(0);
  });

  it('handles multiple event handlers', () => {
    const graph: VisualScriptGraph = {
      nodes: [
        { id: '1', type: 'OnStart', position: { x: 0, y: 0 }, data: {} },
        { id: '2', type: 'SetVariable', position: { x: 200, y: 0 }, data: { key: 'score', value: 0 } },
        { id: '3', type: 'OnUpdate', position: { x: 0, y: 200 }, data: {} },
        { id: '4', type: 'Translate', position: { x: 200, y: 200 }, data: { entity: 'entityId', dx: 0, dy: 0, dz: 0.1 } },
      ],
      edges: [
        { id: 'e1', source: '1', sourceHandle: 'exec_out', target: '2', targetHandle: 'exec_in' },
        { id: 'e2', source: '3', sourceHandle: 'exec_out', target: '4', targetHandle: 'exec_in' },
      ],
    };
    const result = compileGraph(graph);
    expect(result.success).toBe(true);
    expect(result.code).toContain('function onStart()');
    expect(result.code).toContain('function onUpdate(dt: number)');
    expect(result.code).toContain('forge.state.set');
    expect(result.code).toContain('forge.translate');
    expect(result.errors.length).toBe(0);
  });
});
